### ISSUE TITLE
Wrong registration page behind the link

### ISSUE THREAD

**Issue by msedd** [Ableton/ableton.github.io#13]
The registration link for Ableton Link is wrong.
`To request access to LinkKit please register here.`
https://www.ableton.com/en/link/sdk/license-request/

The content behind this link is for the other SDK (Ableton Live Set Export)

**Comment by fgo-ableton** [comment]
@msedd Thanks for letting us know! We removed the request access form for LinkKit recently. I had only updated the wording on the LinkKit page but forgot about the main page. I pused a fix: https://github.com/Ableton/ableton.github.io/blob/master/index.md

**Comment by msedd** [comment]
Thanks!
The integration of the library works fine.
