### ISSUE TITLE
No answers

### ISSUE THREAD

**Issue by jpnielsen** [Ableton/ableton.github.io#16]
I'm curious about why there is no answer on issues in this repository.

Push2 was expensive enough, I don't think you should have put up the repository if you're not going to keep it up to date with Visual Studio and JUCE releases.

https://github.com/Ableton/push2-display-with-juce

**Comment by nre-ableton** [comment]
Hi @jpnielsen -- sorry about this! We do our best to keep open-source repos such as this updated, but this one had fallen through the cracks and we hadn't realized that it had fallen behind VS/JUCE. I've spoken with the maintainer and we've agreed to archive the repository, which means that the source code will still be online for reference purposes, but this will avoid confusion as to the state of the repo with regards to IDE/JUCE framework support.

Sorry for the confusion!
