### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by hel-ableton** [Ableton/ableton.github.io#4]
Could someone (Gilbert?) add a meaningful README to this repo? It would be nice to know just what it's getting used for! (I know, we talked about it at lunch. But... I forgot!)

**Comment by ghost** [comment]
@hel-ableton README is now in!

**Comment by hel-ableton** [comment]
Nice! Although it would still be cool to also mention something about the purpose/content/audience of that site?

**Comment by hel-ableton** [comment]
(For example, why can I not call ableton.github.io in the browser?)

**Comment by ghost** [comment]
You are right, will do that in a second step.

**Comment by mst-ableton** [comment]
@hel-ableton do you think we can close this now?

**Comment by hel-ableton** [comment]
@mst-ableton - yes, sure!
